language: cpp
compiler: gcc

addons:
  apt:
    packages:
      - cmake
      - lcov
      - libgtest-dev
      - python3-pip  # Для coveralls-lcov

before_install:
  - pip3 install --user cpp-coveralls  # Установка coveralls-lcov

before_script:
  - mkdir -p build
  - cd build
  - cmake -DENABLE_COVERAGE=ON ..

script:
  - cmake --build .
  - ctest --output-on-failure

after_success:
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' '*/tests/*' '*/_deps/*' --output-file coverage.info
  - coveralls-lcov coverage.info

